### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by bszedwardwo** [bszedwardwo/protospace-32079#1]
https://protospace-32079.herokuapp.com/

**Comment by spoongit** [comment]
十亀（bszedwardwo）さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

・空のコメントでは保存されない
空のまま保存しようとすると投稿ができずにそのページにとどまるよう実装しましょう！
（現在は空のコメント投稿時にエラー文が表示される状態です）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by spoongit** [comment]
十亀（bszedwardwo）さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願い致します。

・空のコメントでは保存されない
空のまま保存しようとすると投稿ができずにそのページにとどまるよう実装しましょう。
（現在は空のコメント投稿時にページ遷移し、エラー文が表示される状態です）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by bszedwardwo** [comment]
すいませんherokuにアップロードしてなかったです・・・！アップロードしました、お願いします！

**Comment by spoongit** [comment]
十亀（bszedwardwo）さん、herokuアップロードとご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
